---
title: "Algorithm Design and Theoretical Basis Description"
subtitle: "Technical Note D2"
author: "Krasen Samardzhiev, Barbara Metzler, Martin Fleischmann, Dani Arribas-Bel"
institute: "Charles University; The Alan Turing Institute"
format:
  pdf:
    toc: true
    number-sections: true
    colorlinks: true
  html:
    toc: true
    css: styles.css

bibliography: ../references.bib
---

<!-- This tries to closely match what was promised in the project proposal. -->

# Exective summary

Summary goes here.

# Theroetical basis

Kind of lit review I suppose? Probably could be adapted stuff we have in the proposal.

## Morphometric Classification Homogenisation

The spatial layout of the physical elements of cities affects most activities their residents undertake, from accessing services or jobs to their social and cultural lives.
Analysing the interplay of this urban fabric, with land use, mobility or other dimensions of human activities provides insights into how cities evolve and what effective developmental policies should look like.
Researchers in the field of urban morphology have spend years in identifying, classifying and analysing the variations in urban form across cities from all over the world.
A core new development, powered by advancements in geographic data science, GIS tooling and computer vision, is the methodologies created to computationally discern and analyse urban fabric [@fleischmann2022methodological].
Taken together, these facts have opened up the possibility of a more systematic and comprehensive approach to the classification of urban morphological patterns, which in turn can drive our understanding of cities [@calafiore2023inequalities ; @arribas2022spatial].

One factor that limits the wider application of these methods is their dependancy on high-quality data, that is generally not available for every city.
For example, [@fleischmann2022methodological ; @arribas2022spatial] use building polygons from the respective countries' cadastres.
However, such data is not generally available even for most high-income countries.
And where available, it can come in various formats and the data itself is not necassarily homogenous, which makes its processing difficult.
For example, official Czechia building polygons (https://services.cuzk.cz/) come as a geopackage, with no information about building age, height, type or use.
In contrast,  official German building polygons, come seperately for every bundesregion , typically but not always as GML data from a WFS service, and sometimes have extra building information.
However, the definition of building is different to Czechia and the polygon set may include parts of tunnels, overpasses or tram lines.
These definitions are even sometimes different in the cases of cities within the same country - i.e. the data for Berlin and Hamburg is different from the data available for Bremen.

EUROFAB aims to address the data availability and processing issues, as well as broaden the applicability of urban morphometrics.
It does this through the development of a predictive urban morphometric model which uses widely available building footprints to infer urban form.
The model input is calculated directly on satellite-derived building footprints, which gives it a global scope and thus eliminates the need for the data fusion problems described above.
Furthermore, it is trained on a detailed morphometric classification derived from official cadastre data in a large study area that covers multiple countries - Poland, Austria, Czechia, Germany and Slovakia, i.e. Central Europe [@primus].
The heterogeneity of urban forms and planning regimes present in the study area enables the model to distinguish a rich variety of urban patterns and improves it generalisability.

The specific approach we take this has four stages.
In the first stage morphological elements and their characteristics are calculated for the study area using the widely available Microsoft building and Overturestreemaps data.
These elements are the predictor variables that the model will use. To achieve this we develop a highly-scalable polygon and street data pipeline, capable of calculating an exhaustive list of morphometric characteristics.
In the second stage, each element, calculated in the first stage, is assigned a target classification label based on spatial overlap with morphological elements from [@primus].
[@primus] is a classification of urban fabrics in Central Europe based on the highest-detail available cadastre data.
Third, the data is then split into training and testing subsets based on spatial contiguity, in order to account for spatial leakeage.
Lastly, two models - a random forest and boosted trees model - are compared in a clasification task that aims to predict the morphological classification of individual elements, using a custom validation schema.
The custom validation schema is required in order to empasize in the evaluation, the model's ability to deal with previously unseen data and new urban fabric types.
The best performing model is chosen as the final production model, and retrained on the whole dataset.
The motivation for using the classification models is that they will be able to combine the calculate morphological elements in non-linear ways, in order to account for the shortcomings of the satellite-derived building footprints.

<!--Satellite derived building footprints intro-->
Satellite derived building footprints are becoming more widely adopted, however, the data does not come without issues.
For example, in dense urban centres entire blocks can be delineated as individual buildings.
Given that morphology calculations rely on precise local topological relations between neighbours, such as two buildings touching, this problem renders a whole number of possible measurements described in [@fleischmann2021measuring] meaningless. 
Furthermore, this issue affects even simpler calculations such as counting the number of buildings within a radius or topological neighbourhood.
Other issues are that computer vision techniques sometimes miss entire buildings or misidentify building boundaries.
Therefore, any approach that uses satellite-derived building footprints should be able to account for these three and potentially other problems.


Implementing these stages, and further realising the potential of the model for global application, requires the creation of novel, scallable data processing pipelines capable of analysing hundreads of millions of morphological elements - buildings, streets and their derivations. 
Due to their scalability, these pipelines can further be reused for other work, outside of the immidiate scope of this projects. 
To ensure maximum impact and high standards, all work for this project follows open science principles and is open-sourced at (github.com).

## AI Modelling using Satellite Imagery

A brief theoretical background.

# Algorithm Design

## Morphometric Classification Homogenisation

### Model architecture

We aim to replicate the methodology of [@primus] as closely as possible, given the issues with the satelite-derived data raised before, as that is the current state of the art approach to generate morphometric classifications. 
We further chose to follow the methodoly of [@primus] for three reasons. 

First, the ETC concept is space filling, which means that we can account for some of the missing buildings problems - areas with missing buildings will still play a role in the classification and will not break contiguity. 
However, even though we are working on the same study area, our ETCs will be different and their measured characters have different interpretations as well.
Second, given fact that we do not know a priori which measurements are most important, or how to combine them, or which ones will be the most affected by the building data issues, we use the full set calculated by [@primus].
This gives us an list of characteristics that capture detailed 2d spatial information about urban morphology, backed up by an extensive literature review.
Third, the existing classification allows us to train our model on its high quality outputs. 
Our approach aims to account for problems of satellite-derived buildings and different values and interpretations of morphological elements, through the use of a classifier to combine the calculated characteristics in non-linear ways.
For example, by weighing more street-related characteristics since the data sources are the same for both, or downplaying shared walls characteristics in urban centres since they are distorted.
We use a model and do not hardcore these rules, since there may be complex relationships between the variables that we do not know a priori.

The data preparation and model training consists of four stages.
The first and second stages cover the morphometric characterisation, which acts as the model's predictor variables, and the target variables generation.
The third stage randomly splits the whole study area into model training and testing data taking into account spatial contiguity.
The final stage is the model training and evaluation, based on a framework in which we empahsize the ability to flag unseen urban fabric types in five different scenarios.
The full model training and evaluation framework will be implemented using scikit-learn pipelines.

### Data preprocessing

### Morphometric characterisation
There are five morphological elements used for the morphometric characterisation - two base ones - buildings and streets and three derived ones - enclosures, nodes, enclosed tessellation cells. 
Additionally, a conceptual unit - a subregion - is defined to speed up processing and scale the analysis.
The subregion is a grouping of buildings that is seperated by at least 400m from other groups of buildings (subregions).
Buildings and streets are the two elements from which all other units are derived.
Enclosures are areas of landmass surrounded by streets, whereas nodes are the points of intersection between streets.
The core unit of analysis in the study is the enclosed tessellation cell, which breaks down the whole study area into small-scale units, which when taken together fully cover the area.

#### Subregions split
Since the study area of interest is large and contains tens of millions of buildings, it is broken it down into subregions to carry out all computation.
The seperation is done based on distances between buildings - buildings are split into subregions such that there is at least 700 metres between a building from one region and its closest neighbour (another building) from another region. 
This custom seperation, rather than official administrative divisions, ensures that all elements that may effect morphological calculations are in the same set (subregion) and not split across political boundaries. 
All processing and character calculations are done for each region independently and in parallel.


#### Building preprocessing
All available Microsoft building footprints for the study area (Central Europe) are used for the analysis.
Typpically, building polgyons required for morphological studies have to be of very high quality.
For example, building polygons overlapping by a thousandth of a milimeter - break topological contiguity and therefore affect the calculation of morphotogical properties, such as the ratio of shared walls, or the number of adjacent buildings. Furthermore, even the highest quality available software suffers from numerical precision issues which exasparate the above problem.
Another potential issue is the inclusion of artefacts we are not directly interested in such as sheds or market stalls.
The footpritns used for this study fall short of these standards.
Therefore, our approach aims to accommodate less than ideal data and methods, first by processing the building data, and second, by adapting the morphological calculations to account for numerical issues.

The first step in the building data processing is to split up multi-polygons and make the geometries valid. 
The second step, is to simplify the polygons in order to accurately represent the corners of buildings and other shape related characteristics.
Next, to filter out any buildings that have an area larger than 200,000 sq.m. This is done since some artefacts such as construction sites, mines or tunnels are included in the data as buildings. 
The next step is to merge overlapping buildings that either: overlap for atleast 10 percent of their areas, or one of them has less than 50 sq.m. in total area. 
This is done to merge buildings and building parts, since cadastre definitions of these two polygon types are inconsistent and sometimes buildings are assigned as building parts or vica versa. 
This step merges the buildings and its parts into one polygon.
Finally, the preprocessing pipeline snaps nearby buildings together and fills gaps in the polygons that are less than 10 square cm. 
These two steps aim to address some common topological issues, such as missing slivers with almost zero areas between multiple or inside individual building polygons.
Nevertheless, even after the preprocessing numerous topological issues remain and therefore we take this into account in subsequent analysis steps.


#### Overture Streets
The street network is a direct download from Overture maps, a processed subset of data from Openstreetmap, which has global coverage and high quality data.
Since the dataset includes multiple segments types, including footpaths, the types of segments used in the analysis are limited to ... . 
Another type of segment that is filtered out are tunnels - the analysis strictly focuses on two dimensions and therefore undergrounds structures adversely affect the calculation of boundaries and characters.


The second major stage of the street processing is the simplification of the entire street network for each subregion. The actual physical layout of the street is not important to the study - the number of lanes for example, or the exact structure of roundabouts. Rather, the focus is on the topological properties of the street network such as connections, as well as general physical characteristics such as lengths and widths. Therefore the overture street network is further processed by eliminating false nodes, combining lanes and simplifying roundabouts.
<!--- this needs more explanation -->


#### Derived data

##### Nodes
The first type of derived element in the study are street nodes, which are defined as the intersection points between different streets. 
They are used to caclucate characteristics of the street network that capture relationships betwee streets such as number of intersections, as well as relationships between neighbouring enclosures and ETCs.

##### Enclosures
Enclosures capture the characteristics of plots of land that contain multiple buildings. 
They are operationalised as land deliniations, surrounded by streets, which can vary in size depending on the geographic context. 
If an area is in the city centre, each enclosure would approximate a single block and multiple building units, however if it was in an industrial area it would potentially encompass a single, or very few large buildings.
Furthermore, enclosures are used to delineate the boundaries of enclosed tessellation cells to the surrounding streets - i.e. representing physical barriers.

##### Enclosed Tessellation Cells
Enclosed Tessellation Cells are the core unit used for the analysis and the one used to combine aspects of all of the other four elements. 
To operationalise it, the study follows the definition by [@fleischmann2022methodological] - “the portion of space that results from growing a morphological tessellation within an enclosure delineated by a series of natural or built barriers identified from the literature on urban form, function and perception” . Where a morphological tessellation is a deliniation of the space, based on voronoi polygons centered around buildings.
And in this study, only the street network is used for barriers.
The boundaries of ETCs also represent the closest area of land to each building, than to any other building within an enclosure. Because of this feature, ETCs intersect with all other elements and are the unit that links together the characteristics of the four other elements.
In some cases, if there are no buildings within the enclosure the whole enclosure is treated as an 'empty' tessellation cell.

In this study, ETC deliniation is further modified by introducing a variable, individual limit for every ETC, as opposed to the global one used by [@fleischmann2022methodological].
This is done to limit the boundaries effects around the edges of cities and towns - i.e. ETCs on the edges of cities in [@fleischmann2022methodological] are always large because there are no surrounding buildings and their ETCs resemble those of large buildings with lots of empty space around them.
The ETC limits used here are calculated through a Garbriel filtration of the subregion, which takes into account the surrounding neighbours structure around every ETC.
For example, in  row housing the buffer will be relatively small, in single family housing estates the buffer will be larger, and in industrial areas larger still; regardless of whether or not these buildings are in the middle of cities or around their edges.

##### Morphometric Characters
Characteristics describing the interactions of these elements, and the elements themselves are calculated at three scales: small - covering only aspects of the element; medium - covering aspects of the element and neighbouring elements and large - covering neighbouring elements up to five topological neighbours.
In total there are 63 prime characters calculated described in Appendix A, which come directly from the lirateture review carried out by [@fleischmann2021measuring].

### Target labels
For the second stage, we assign a target classification label to every ETC derived using the satellite-derived polygons. 
This is done based on spatial intersection between EUROFAB and [@primus] ETCs.
In cases where there are multiple detailed tessellation cells that fall within the range of a single EUROFAB ETC, the label is decided based on majority.

Since the final output of [@primus] is a hierarchy, rather than a flat clustering there are several options how to pick the specific target labels.
Generally, clusters lower in the hierarchy represent classifications of urban fabrics at more granular scales. For example, depending on the hierarchy cutoff point historical urban areas can be one cluster, or can be seperated into two - medieval and industrial-era urban fabrics.

The specific selection of cutoff points will follow [@primus].
The first set of urban fabrics we will aim to predict, broadly deferentiates -  different types of houses; from heterogenous historical urbanised areas; from recent modern urban developments - apartment blocks and industrial areas.
The second set breaks down each of the first sets into multiple subsets.
It goes into more detail and splits the houses into more classes, based on features such as size and proximity to cities; it also splits the historical areas based on origin - medieval, industrial-era and others; and splits the modern urban developments into subclasses such as modernist apartment blocks, industrial areas, offices and others.
By analysing the model performance across two different hierarchical levels, we will understand what is the highest resolution detail the model can predict, given the shortcomings of the data and which factors affect predictions.


### Train/test/validation split

After assigning the target labels, we create a schema that will dictate how to split the data into a training and testing subsets for the classification models.
Random subsetting does not work for this study, since we need to account for spatial leakage between train and test data. The spatial leakage comes from both the nature of the data - spatial contiguity is one of the core aspects of morphological elements - but also from the way characters are calculated based on various nearest topological neighbours.

To account for this, we aggregate nearby ETCs into higher granularity spatial units - level 5 h3 cells - and randomly split the these units into 80% train and 20% test data, based on contiguity.
This ensures that the majority of the test set ETCs and their neighbours are not present in the training data and no morphological characters related to them affect the training set.
We use level 5 H3 cells, which represent a deliniation of the globe into hexagons with approximately 250 sq. km. area, rather than enclosures or ETC contiguity, to ensure that contigious subsets of test data cover areas of heterogenous elements and present the model with a realistic validation scenario.
This process is done once for the whole study area, before training any models.

### Training and validation

<!--why classification and tree based methods-->
The main aim of the modeling task is to generate a classification of morphological elements of similar quality to [@primus] given the data quality limitations.
To achieve this we create an evaluation framework for two tree-based models - a random forest classifier and an xgboost model.
We use the satellite-derived ETCs and their characteristics as input data and the clusters from [@primus] as target labels for a classification task.
The choice of tree-based learning models is due to their readily available implementations, high scalability and ability to quickly offer iterpretation insights.
Furthermore, they handle well high dimensional data, non-linear interactions and require minimal hyperparameter tuning. The flexibility of the models and the specific training/testing framework setup will allow us to not just produce a predictive model but also to identify potential areas for improvement in the original data preprocessing.

<!--out of sample importance-->
Since we want the final production model to be general and aplicable to large areas i.e. whole continents, it needs to be able to handle previously unseen urban fabric types.
For example, an urban morphology type that is present in the test data, or in another study area, might not be present in the training data and in that case the model should flag its predicted label as uncertain.
This is another area where tree models have an advantage, since they are ensamble methods and this can help reduces their tendancy to overfit. They also readily provide a confidence score for each prediction which can be used to flag unseen data.
Furthermore, we take extra care to evaluate the final production models performance in realistic scenarios and the relationship between its accuracy on test data and whole countries that are not part of the model training or test data.


<!--evaluation setup-->
To achieve this we train five iterations of each model on different subsets of the study area - so that that every country and every combination of countries is used as final hold-out validation data a and train/test pipeline respectively. For example, one iteration will use Germany, Poland, Czechia and Austria as part of its train/test pipeline, whereas Slovakia will be used as the hold-out data , in order to see the relationship between the final test score from the train/test pipeline and the models realistc performance on a whole unseen country's urban fabric.
The data from the four countries in each train/test pipeline will be separated into training and test sets based on the spatial strategy described previously.
The model training and evaluation will follow standard best practices - model coeffiecients and hyper parameter tuning, such as the decision threshold will be optimised based on the training subset, and the test subset will be used to give a final model accuracy score.
Specifically, the models will use balanced accuracy as the optimisation metric in order to account for imbalances in the distribution of urban fabric classes. Our framework further extends the best practices with an additional layer of testing using the hold-out country for each train/test pipeline.
All of the data in the hold-out country is used to score the model's performance and the spatial train/test split will be ignored for that particular iteration.

This acts as an extra check against overfitting and ultimately enable us to see how the final production model will perform in realistic scenarios - applying it to whole countries which are not used for the training or testing at all.
This comes with at least two advantages over simply reporting a test score on a random sample.
First, it is a test of model performance on a dataset that does not have any spatial leakage with the training or testing data.
Second, it ensures that we evaluate model performance on unseen urban fabric types from other countries. We can afford to do this in part due to the large size of the data we are working with.
In every permutation there will be a rich variaty of urban fabrics and tens of millions of ETCs used in the training part of each train/test pipeline.

The final production model is trained on the whole dataset, using the same hyper parameter grid search configuration and traing/test spatial split.
The choice between the xgboost and random forest models will be decided based on the results from the framework.
The extra validation steps we carry out with the hold-out countries will be used to used in three ways.
First, to contextualise the final models' accuracy on the test data; second, to indicate how the model will perform on other countries; and third to see how it handles urban fabric types not seen in the training or test data in a realistic scenario.


### Preliminary results

There are 56,845,150 Microsoft building footprints for our study area, which are split into 474 sub-regions.
This is significantly less than the available cadatestre data, which has around 88 million buildings and are seperated into 828 regions.
The number of downloaded, unprocessed streets is similar to those in [@primus] - 23,332,865 - since they cover the same study area and come from the same source - Overture Maps, which is a processed subset of Openstreepmap. 
However, the number of tesselation cells is the same as the buildings and therefore less than the cadastre data-based classification.
Furthermore, the street simplification algorithm is affected by the available buildings, and therefore in turn also affects the tessellation cell boundaries. 
These results highlight the problems with the satellite derived building footprints that have been discussed above - the missing or wrongly merged building polygons.
In turn these affect the third discussed issue - the interpretation of the values of the calculated morphological characters. Many characters from the original classification also completely lose their meaning.
For example, the number of adjacent buildings in the EUROFAB dataset is much smaller and therefore all characters based on adjacency have a much more limited utility.
This also affects, to a relatively smaller, but nevertheless important extent, characters that rely on inter-building distances and counts.

These results futher point towards the need for a non-linear classification model, cable of accounting for these data discepencies.



## AI Modelling using Satellite Imagery

Most of the stuff from `technical_part_turing.qmd` except the data description.

### Data preprocessing

### Train/test split

### Unbalanced dataset

### Model architectures

#### Baseline approach (Approach A)

#### Segmentation (Approach B)

#### Classification (Approach C)

### Evaluation Metrics

### Preliminary results

# Discussion

# Next steps