---
title: "Reference Data Selection"
subtitle: "Technical Note D1"
author: "Krasen Samardzhiev, Barbara Metzler, Martin Fleischmann, Dani Arribas-Bel"
institute: "Charles University; The Alan Turing Institute"
format:
  pdf:
    toc: true
    number-sections: true
    colorlinks: true
  html:
    toc: true
    css: styles.css
bibliography: ../references.bib
---

# Executive summary

Summary goes here.


# Moprhological data


## Ground truth classification

The main aim of this project is to create a predictive model that is capable of classifying urban fabric.
To achieve this we need to use existing urban fabric classifications as ground truth data, and we have picked the [@primus] classification.
It the only avaialbe classification that fully covers our study area and is based on the highest quality data available.
It extends the work of [@fleischmann2022methodological], which has been used in numerous subsequent studies and official planning documents [@calafiore2023inequalities ; @arribas2022spatial; @samardzhiev2022functional] .

@primus use a combination of buildings and streets to generate Enclosed tessellation cells, which are spatial units that are centred around buildings, and encapsulate the surrouning space that is nearest to them, rather than other buildings. Its boundary is also limited by streets or a preset buffer distance from the centre of the building, which acts as the centre of the ETC. 
It is from the combination of buildings, streets and space, that the ETC can combine morphological characteristics of both streets and buildings.
The next step in @primus is to measure different characteristics (or chars) of the fundamental unit. 
A literature review carried out by (Measuring urban form) suggests that there are around 80 unique ones that take into account the two dimensional nature of the data. 
[@fleischmann2022methodological] use the full array of characters since they dont know a priori which will be the important variables. 
The detailed list of characters is presented in the Algorithm design technical note, since both our method and [@primus] share the same characters.
The next steps combine the data using different types of clustering to extract the final urban fabric types.

More detailed information about the primus methodology is available in the algorithm-design document, as we aim to follow it as closely as possible in our method.

## Building footprints
 
Building footprints are one of the two core elements needed to generate morphometric classifications.
Measurements of aspects of buildings provide the bulk of the information about the morphological character of a place.
Many characters in the literature [@fleischmann2021measuring], for example the ratio of perimeter shared with other connected buildings, require very high quality building footprints to accurately reflect the reality of the underlying topology.
There are numerorous available source of building footprints - cadastre, openstreetmap, satellite data, overture .
Which come with their own drawbacks and advantages.

### Available sources
The highest quality available one is official cadastre building footprints.
These provide the groundtruth of planning and adiminsitrative applications in many countries.
However the data is not always available - for example its not easy to download hungarian data, and german data is split across the 16 bundesregions.
Not always reflective of the urban reality - for example in Czechia the official cadastre reflects shared administration in some modernist apartment blocks, rather than the physical structure of the buildings.

Another source is openstreet map, which is free and open geographical database generated by volunteers.
In many cases the cadastre data is processed and put into openstreetmap, alongside volunteer contibutions where official data is missing.
The issues  with open streetmap data are similar to cadastre data in that its not always easy to process and the quality is unequal.
For example the data in Germany is very high quality, but in not in other countries like Italy or Bulgaria.

Another available data source is satellite-derived building footpritns.
Satellite derived building footprints are becoming more widely adopted due to advanced in satellite techonolgy and computer vision algorithms. 
They have sucessfully been used in applications for city boundary delineation, disegregating population and others. 
There are multiple sources of global building footprints available - Google building footprints, Microsoft building footprints, Overture maps that combines various other sources, as well as other proprietary data.
The problems with satelite data is that the quality is incosistent and the topology is many times broken.

The newest available data source is Overture maps, which combines all of these data sources.
Overture is based off of Openstreetmap and treats it as the ground truth data and has a hierarchical structure.
The buildings from Openstreetmap are considered the groundtruth and buildings from additional sources such as satellite data are added where there is no openstreetmap data.
This means that in general it has the highest number of available buildings.
However, it comes with the problem that the buildign data is heterogenous - in different places different data sources with different charactersitics are merged.
This makes working with the data more difficult than other resources.

Similarly, EUBUCCO is another data source that combines multiple datasets.
Unfortunately, it has lots of missing data and is a mix of official and Openstreemap data.

### Microsoft building footprints
In this study, we use the Microsoft building footprints since they fully cover our study area - Central Europe.
The dataset also has good worldwide coverage and the footprints are derived in a consistent way, which ensures scalability of our method to different countries.
It should be noted that our approach can also work for other consistently derived building polygons, Google Footprints for example, so long as all the data is generated from the same source.

However, the data does not come without issues. 
For example, in dense urban centres entire blocks can be delineated as individual buildings.
Given that morphology calculations rely on precise local topological relations between neighbours, such as two buildings touching, this problem renders a whole number of possible measurements described in [@fleischmann2021measuring] meaningless. 
Furthermore, this issue affects even simpler calculations such as counting the number of buildings within a radius or topological neighbourhood. Other issues are that computer vision techniques sometimes miss entire buildings or misidentify building boundaries.
Therefore, any approach that uses satellite-derived building footprints should be able to account for these three and potentially other problems.

## Street data
Street network data is the other major data source used in numerical morphometric analysis.
It is used to calculate spatial relationships, morphological features and deliniate boundaries for other elements.
There are numerous sources for street network data, however the major one is Openstreetmap.

### Overture transportation layer

The street network used in this study is a direct download from Overture maps, a processed subset of data from Openstreetmap, which has global coverage and high quality data. 
We use overture directly due to the fact that its more accessable and contains information on the type of street that, in a format, is easier to process.
However the underlying geometry of the two data sources is identical.

Since the dataset includes multiple segments types, including footpaths, the types of street segments used in the analysis are limited to the ones  in Table 1.

| *Types of streets*  |
|----------------|
| living_street  |
| motorway       |
| motorway_link  |
| pedestrian     |
| primary        |
| primary_link   |
| residential    |
| secondary      |
| secondary_link |
| tertiary       |
| tertiary_link  |
| trunk          |
| trunk_link     |
| unclassified   |

Another type of segment that is filtered out are tunnels - the analysis strictly focuses on two dimensions and therefore undergrounds structures adversely affect the calculation of boundaries and characters.



# AI data